name: Deploy to production using docker
on:
    push:
        branches: [ prod ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
        
            - name: Docker login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
            
            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: chetanvaswani/helloworld:${{ github.sha }}
            - run: |
                echo "${{ secrets.SSH_KEY }}" &> ~/ssh_key
                chmod 700 /home/runner/ssh_key
                ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.SERVER_IP }} -t "
                sudo docker stop helloworld &&
                sudo docker rm helloworld &&
                sudo docker run -d --name helloworld -p 3000:3000 chetanvaswani/helloworld:${{ github.sha }}"



