name: Commit to Production server
on:
  push:
    branchs: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ssh into server
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: {{ secrets.SERVER_IP }}
          username: {{ secrets.SSH_USER }}
          key: {{ secrets.SSH_KEY }}
          script: |
             cd helloworld || exit
             git pull || git clone https://github.com/chetanvaswani/helloworld.git
             bun install
             pm2 restart helloworld


